// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASZHVVfMOKk-8ZPvnbGrLzupjE37t_q8Q',
    appId: '1:1084417434100:web:cd0bd2706139ce5c4159a1',
    messagingSenderId: '1084417434100',
    projectId: 'mixmasters-91a3d',
    authDomain: 'mixmasters-91a3d.firebaseapp.com',
    storageBucket: 'mixmasters-91a3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiq64-dceouGsjRQxCKwoUruHuzyDOasw',
    appId: '1:1084417434100:android:6a36567bb3ecebfc4159a1',
    messagingSenderId: '1084417434100',
    projectId: 'mixmasters-91a3d',
    storageBucket: 'mixmasters-91a3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPdM7lF0LmISCcLscQTsSHxjLt-9JxK6U',
    appId: '1:1084417434100:ios:c4700cfa86d9ce174159a1',
    messagingSenderId: '1084417434100',
    projectId: 'mixmasters-91a3d',
    storageBucket: 'mixmasters-91a3d.appspot.com',
    iosBundleId: 'com.example.salarySlip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPdM7lF0LmISCcLscQTsSHxjLt-9JxK6U',
    appId: '1:1084417434100:ios:c4700cfa86d9ce174159a1',
    messagingSenderId: '1084417434100',
    projectId: 'mixmasters-91a3d',
    storageBucket: 'mixmasters-91a3d.appspot.com',
    iosBundleId: 'com.example.salarySlip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASZHVVfMOKk-8ZPvnbGrLzupjE37t_q8Q',
    appId: '1:1084417434100:web:7706c22b1f844fa84159a1',
    messagingSenderId: '1084417434100',
    projectId: 'mixmasters-91a3d',
    authDomain: 'mixmasters-91a3d.firebaseapp.com',
    storageBucket: 'mixmasters-91a3d.appspot.com',
  );
}
